{
  "hash": "b58949ccd111aecc0e90a97525af4b90",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab: Logistic Regression\"\nsubtitle: \"Princeton University\"\nauthor: \"Chantal Valdivia-Moreno\"\noutput: \n  tufte::tufte_html:\n    css: \n    tufte_variant: \"envisioned\"\n    highlight: github-dark\n    fig_height: 10\n    fig_width: 16\n    toc: true\n    toc_depth: 1\nexecute: \n  message: false\n  warning: false\nformat: \n  html:\n    code-fold: true\n    code-overflow: wrap\nengine: knitr\n---\n\n\n\n\n-   Assignment requirements:\n\n    -   If you are using Github (recommended), make sure to commit and push your work to GitHub regularly, at least after each exercise. Write short and informative commit messages, and share the link to your assignment with me. If not, you can also send me the **rmd** & **rendered file** via Canvas.\n\n    -   In this assignment, you will not need to code from scratch. Rather, you'll need to fill in code where needed. This assignment has a logisitic regression implementation for a scenario from EDA down to model comparison (and would be useful for whenever you may encounter such a situation in the future).\n\n    -   I want the assignments to begin reflecting a bit more of how you'd be doing things on your own, where you have some prior knowledge and you figure other things out (by referring to documentation, etc.) . In addition to the rmd, I also want you to submit to me **notes** of anything new that you learn while finishing the assignment. And any pain-points, and we'll discuss more.\n\n        -   In general I struggled with this assignment due to the length and just being unclear on some of the points (like what a question was asking) but otherwise I liked this new format of assignment where there were chances to verify your work and repeat some of the same skills.\n\n        -   I like anything where we build with ggplot\n\n        -   Maybe some more hints throughout could be helpful?\n\n-   Note:\n\n    -   If you are fitting a model, display the model output in a neatly formatted table. (The `gt` `tidy` and `kable` functions can help!). `Modelsummary` also looks good(https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html)\n\n    -   Make sure that your plots are clearly labeled – for all axes, titles, etc.\\\n\n## Data: General Social Survey\n\nThe General Social Survey (GSS) has been used to measure trends in attitudes and behaviors in American society since 1972. In addition to collecting demographic information, the survey includes questions used to gauge attitudes about government spending priorities, confidence in institutions, lifestyle, and many other topics. A full description of the survey may be found here.\n\nThe data for this lab are from the 2016 General Social Survey. The original data set contains 2867 observations and 935 variables. We will use and abbreviated data set that includes the following variables:\n\nnatmass: Respondent’s answer to the following prompt:\n\n“We are faced with many problems in this country, none of which can be solved easily or inexpensively. I’m going to name some of these problems, and for each one I’d like you to tell me whether you think we’re spending too much money on it, too little money, or about the right amount…are we spending too much, too little, or about the right amount on mass transportation?”\n\nage: Age in years.\n\nsex: Sex recorded as male or female\n\nsei10: Socioeconomic index from 0 to 100\n\nregion: Region where interview took place\n\npolviews: Respondent’s answer to the following prompt:\n\n“We hear a lot of talk these days about liberals and conservatives. I’m going to show you a seven-point scale on which the political views that people might hold are arranged from extremely liberal - point 1 - to extremely conservative - point 7. Where would you place yourself on this scale?”\n\nThe data are in gss2016.csv in the data folder.\n\n## EDA\n\n> Let’s begin by making a binary variable for respondents’ views on spending on mass transportation. Create a new variable that is equal to “1” if a respondent said spending on mass transportation is about right and “0” otherwise. Then plot the proportion of the response variable, using informative labels for each category.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# loading required packages\nif (!require(\"dplyr\")) {install.packages(\"dplyr\"); require(\"dplyr\")}\nif (!require(\"ggplot2\")) {install.packages(\"ggplot2\"); require(\"ggplot2\")}\nif (!require(\"readr\")) {install.packages(\"readr\"); require(\"readr\")}\nif (!require(\"modelsummary\")) {install.packages(\"modelsummary\"); require(\"modelsummary\")}\nif (!require(\"tidyr\")) {install.packages(\"tidyr\"); require(\"tidyr\")}\nif (!require(\"knitr\")) {install.packages(\"knitr\"); require(\"knitr\")}\nif (!require(\"easystats\")) {install.packages(\"easystats\"); require(\"easystats\")}\nif (!require(\"broom\")) {install.packages(\"broom\"); require(\"broom\")}\nif (!require(\"emmeans\")) {install.packages(\"emmeans\"); require(\"emmeans\")}\nif (!require(\"marginaleffects\")) {install.packages(\"marginaleffects\"); require(\"marginaleffects\")}\nif (!require(\"performance\")) {install.packages(\"performance\"); require(\"performance\")}\nif (!require(\"arm\")) {install.packages(\"arm\"); require(\"arm\")}\nif (!require(\"modelsummary\")) {install.packages(\"modelsummary\"); require(\"modelsummary\")}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- read.csv(\"gss2016.csv\")\n```\n:::\n\n\n\n\nFill in the \"\\_\\_\\_\\_\" below to encode the binary variable\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n   mutate(mass_trans_spend_right = if_else(natmass == \"About right\", 1, 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Get proportions\nmass_spend_summary <- data %>%\n  count(mass_trans_spend_right) %>%\n  mutate(proportion = n / sum(n))\n\n#Look at the dataframe structure. And make sure it's in a format that you can use for plotting.\n#Change structure if needed\nmass_spend_long <- pivot_longer(mass_spend_summary, names_to = \"opinion\", values_to = \"proportion\", cols = proportion)\n\n#Factorise for plot\nmass_spend_long$mass_trans_spend_right <- as.factor(mass_spend_long$mass_trans_spend_right)\n\n#Make plot\n#Hint: geom_bar lets you make stacked bar charts\nggplot(mass_spend_long, aes(x = opinion, y = proportion, fill = mass_trans_spend_right)) +\n  geom_bar(stat = \"identity\") +\n  scale_fill_manual(values = c(\"#fee8c8\",\"#fdbb84\"),\n    labels = c(\"Not right\", \"About right\")) + \n  labs(title = \"Propotion of responses on mass transportation item\",\n       x = \"Opinion\",\n       y = \"Proportion\",\n       fill = \"Opinion\")\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\n> Recode `polviews` so it is a factor with levels that are in an order that is consistent with question on the survey. Note how the categories are spelled in the data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n  mutate(polviews = factor(polviews,\n                           levels = c(\"Extremely liberal\", \"Liberal\", \"Slightly liberal\", \n                                      \"Moderate\", \"Slghtly conservative\", \"Conservative\", \n                                      \"Extrmly conservative\"),\n                           ordered = TRUE))\n```\n:::\n\n\n\n\n> Make a plot of the distribution of `polviews`\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Get proportions, format, and produce a plot like you did previously for mass_trans_spend_right\n\n#Get proportions\npol_view_summary <- data %>%\n  count(polviews) %>%\n  mutate(proportion = n / sum(n))\n\n#Make plot\n#Hint: geom_bar lets you make stacked bar charts\nggplot(pol_view_summary, aes(x = polviews, y = proportion, fill = polviews)) +\n  geom_bar(stat = \"identity\") + \n    scale_fill_manual(values = c(\"#fef0d9\",\"#fdd49e\", \"#fdbb84\", \"#fc8d59\",\"#e34a33\", \"#d7301f\", \"#990000\")) +\n    labs(title = \"Proportion of responses on mass transportation item\",\n    x = \"Political views\",\n    y = \"Proportion\",\n    fill = \"Political view\")\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n> Which political view occurs most frequently in this data set?\n>\n> **Moderate**\n\n> Make a plot displaying the relationship between satisfaction with mass transportation spending and political views. Use the plot to describe the relationship the two variables.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>%\n  group_by(polviews) %>%\n  summarize(prop_satisfied = mean(mass_trans_spend_right), na.rn = T) %>% \n  ggplot(aes(x = polviews, y = prop_satisfied, fill = polviews)) + \n  geom_bar(stat = \"identity\") +\n  labs(title = \"Proportion of responses on mass transportation item\",\n       x = \"Political views\",\n       y = \"Proportion satisfied with spending\",\n       fill = \"Opinions\") \n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\nThe more conservative one's political views are the more they think the amount of spending on mass transportation is correct.\n\n-   We’d like to use age as a quantitative variable in your model; however, it is currently a character data type because some observations are coded as \"89 or older\".\n\n> Recode age so that is a numeric variable. Note: Before making the variable numeric, you will need to replace the values \"89 or older\" with a single value.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata = data %>%\n  dplyr::mutate(age = if_else(age == \"89 or older\", \"89\", age)) %>%\n  dplyr::mutate(age = as.numeric(age))\n```\n:::\n\n\n\n\n> Plot the frequency distribution of age.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |> \n  ggplot(aes(x = age)) + \n  geom_density(binwidth = 5, fill = \"orange\") + \n  labs(title = \"Frequency distribution of age\",\n       x = \"age\",\n       y = \"frequency\")\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\n## Logistic regression\n\n> Let’s start by fitting a logistic regression model with just the intercept\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintercept_only_model <- glm(\n  mass_trans_spend_right ~ 1,\n  data = data,\n  family = binomial(link = \"logit\"))\n\nintercept_only_model %>% \n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  term        estimate std.error statistic p.value\n  <chr>          <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)    0.119    0.0394      3.02 0.00249\n```\n\n\n:::\n:::\n\n\n\n\n> Interpret the intercept in the context of the data. You can do this by converting the $\\beta_0$ parameter out of the log-odds metric to the probability metric. Make sure to include the 95% confidence intervals. Then interpret the results in a sentence or two--what is the basic thing this probability tells us about?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb0 <- coef(intercept_only_model) # get coef\n\nb0_transformed <- exp(b0) / (1 + exp(b0)) # logistic transform\n\nci_lower = b0 - 1.96 * 0.0393685\nci_upper = b0 + 1.96 * 0.0393685\n\n#transforming confidence intervals of coefficients into probabilities\np_lower = exp(ci_lower)/(1+exp(ci_lower))\np_upper = exp(ci_upper)/(1+exp(ci_upper))\n\nb0_transformed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n  0.5297297 \n```\n\n\n:::\n\n```{.r .cell-code}\np_lower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n  0.5104727 \n```\n\n\n:::\n\n```{.r .cell-code}\np_upper \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n  0.5488986 \n```\n\n\n:::\n:::\n\n\n\n\nInterpretation: About 53% with a 95% CI of 0.51 to 0.55 of people support the policy\n\n> Now let's fit a model using the demographic factors - `age`,`sex`, `sei10` - to predict the odds a person is satisfied with spending on mass transportation. Make any necessary adjustments to the variables so the intercept will have a meaningful interpretation. *Neatly display the model coefficients (do not display the summary output)*\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#make sure that sex is a factor (i.e. to make sure R knows it's binary/categorical, and not continuous)\ndata <- data %>% \n  mutate(sex_clean = as.factor(sex))\n\n#fit with glm()\nm1 <- glm(\n  mass_trans_spend_right ~  age + sex + sei10,\n  data = data,\n  family = binomial(link = \"logit\"))\n\n#produce tidy output of model coefficients\nm1 %>%\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term        estimate std.error statistic       p.value\n  <chr>          <dbl>     <dbl>     <dbl>         <dbl>\n1 (Intercept)  0.825     0.140        5.91 0.00000000332\n2 age         -0.00617   0.00228     -2.70 0.00690      \n3 sexMale     -0.256     0.0798      -3.20 0.00135      \n4 sei10       -0.00623   0.00166     -3.75 0.000177     \n```\n\n\n:::\n:::\n\n\n\n\n> Consider the relationship between sex and one’s opinion about spending on mass transportation. Interpret the coefficient of sex in terms of the logs odds and OR of being satisfied with spending on mass transportation. What are the predicted probabilities for males and females on support for spending on mass transportation? Please include the 95% CIs around each estimate.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 %>% \n  tidy() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |   estimate| std.error| statistic|   p.value|\n|:-----------|----------:|---------:|---------:|---------:|\n|(Intercept) |  0.8254509| 0.1395587|  5.914722| 0.0000000|\n|age         | -0.0061659| 0.0022824| -2.701502| 0.0069027|\n|sexMale     | -0.2557439| 0.0798020| -3.204732| 0.0013519|\n|sei10       | -0.0062271| 0.0016609| -3.749229| 0.0001774|\n\n\n:::\n\n```{.r .cell-code}\nm1 %>% \n  tidy(exponentiate = TRUE) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |  estimate| std.error| statistic|   p.value|\n|:-----------|---------:|---------:|---------:|---------:|\n|(Intercept) | 2.2829100| 0.1395587|  5.914722| 0.0000000|\n|age         | 0.9938530| 0.0022824| -2.701502| 0.0069027|\n|sexMale     | 0.7743403| 0.0798020| -3.204732| 0.0013519|\n|sei10       | 0.9937922| 0.0016609| -3.749229| 0.0001774|\n\n\n:::\n\n```{.r .cell-code}\nbsex <- coef(m1)[\"sexFemale\"]\n\nci_lower_lo = bsex - 1.96 * 0.0798020\nci_upper_lo = bsex + 1.96 * 0.0798020\n\nci_lower_or = 1.29 - 1.96 * 0.0798020\nci_upper_or = 1.29 + 1.96 * 0.0798020\n\nemm_sex <- emmeans(m1, \"sex\", type = \"response\")\n```\n:::\n\n\n\n\nIf you did this right, you'll find that being female (as compared to male) is associated with an increase in the log-odds of being satisfied with spending on mass transportation by 0.2557439 units (95% CI \\[0.09, 0.41\\]), holding all other variables constant. This equates to the odds of thinking the spending amount is right in females being 1.29 times the odds of thinking this in men (95% CI \\[1.13, 1.44\\]).\n\nThe predicted probability for females to be satisfied with spending on mass transportation is 55.9% (95% CI \\[53.3%, 58.5%\\]) and that of males is 49.5% (95% CI \\[46.7%, 52.4%\\]).\\\n\\\nVerify this.\n\n**I think I was able to verify the results of the probability, but the log-odds seem to be inverse for me but the numbers are still correct**\n\n> Next, consider the relationship between age and one’s opinion about spending on mass transportation. Interpret the coefficient of age in terms of the logs odds and OR of being satisfied with spending on mass transportation. Please include the 95% CIs around each estimate.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbage <- coef(m1)[\"age\"]\n\nci_lower_lo_age = bage - 1.96 * 0.002282412\t\nci_upper_lo_age = bage + 1.96 * 0.002282412\t\n\n# odds ratio\nor_age <- exp(bage)\n\nci_lower_or_age = 1.29 - 1.96 * 0.002282412\t\nci_upper_or_age = 1.29 + 1.96 * 0.002282412\t\n\nemm_age <- emmeans(m1, \"age\", type = \"response\")\n```\n:::\n\n\n\n\nA one unit increase in age is associated with a decrease in the log-odds of being satisfied with spending on mass transportation by .006, holding all other variables constant. The odds ratio is 0.994 which confirms the negative relationship implied by the log-odds coefficient. Specifically, for each additional unit of age, the odds of being satisfied with mass transportation spending decrease by a factor of about 0.994, or approximately .006 per unit increase in age, holding other factors constant. (I am not confident in these results)\n\n> Consider the relationship between SES and one’s opinion about spending on mass transportation. Interpret the coefficient of SES in terms of the logs odds and OR of being satisfied with spending on mass transportation. Please include the 95% CIs around each estimate. ß\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbses <- coef(m1)[\"sei10\"]\n\nses_se <- summary(m1)$coefficients[\"sei10\", \"Std. Error\"]\nci_lower_lo_bses = bses - 1.96 * 0.0016609\t\nci_upper_lo_bses = bses + 1.96 * 0.0016609\t\n\n# odds ratio\nor_ses <- exp(bses)\n\nci_lower_or_bses = 1.29 - 1.96 * 0.0016609\t\nci_upper_or_bses = 1.29 + 1.96 * 0.0016609\t\n\nemm_ses <- emmeans(m1, \"sei10\", type = \"response\")\n```\n:::\n\n\n\n\nA one unit increase in SES index is associated with a decrease in the log-odds of being satisfied with spending on mass transportation by 0.0062 units (95% CI \\[-0.0107, -0.0017\\]), holding all other variables constant. The odds ratio is less than 1 (0.9937922), which confirms the negative relationship implied by the log-odds coefficient. Specifically, for each additional unit of SES index, the odds of being satisfied with mass transportation spending decrease by a factor of about 0.993, or approximately 0.7% per unit increase in SES index, holding other factors constant (95% CI \\[0.989, 0.998\\]).\n\n## Marginal effects\n\n-   Let's examine the results on the probability scale.\n\n> Calculate the marginal effects of sex, age, and SES on mass transportation spending. You can use the `margins` package function `margins` discussed in your textbook or you can use the `marginaleffects` package `avg_slope` `avg_comparisons` discussed in lecture. Interpret each estimate.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_comparisons(m1, comparison = \"difference\") %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term  |contrast      |   estimate| std.error| statistic|   p.value|   s.value|   conf.low|  conf.high|\n|:-----|:-------------|----------:|---------:|---------:|---------:|---------:|----------:|----------:|\n|age   |+1            | -0.0015153| 0.0005579| -2.716128| 0.0066050|  7.242217| -0.0026088| -0.0004219|\n|sei10 |+1            | -0.0015304| 0.0004039| -3.789362| 0.0001510| 12.692831| -0.0023219| -0.0007388|\n|sex   |Male - Female | -0.0630688| 0.0196461| -3.210251| 0.0013262|  9.558495| -0.1015743| -0.0245632|\n\n\n:::\n\n```{.r .cell-code}\navg_slopes(m1) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term  |contrast      |   estimate| std.error| statistic|   p.value|   s.value|   conf.low|  conf.high|\n|:-----|:-------------|----------:|---------:|---------:|---------:|---------:|----------:|----------:|\n|age   |dY/dX         | -0.0015151| 0.0005577| -2.716570| 0.0065962|  7.244144| -0.0026082| -0.0004220|\n|sei10 |dY/dX         | -0.0015301| 0.0004037| -3.789984| 0.0001507| 12.696444| -0.0023214| -0.0007388|\n|sex   |Male - Female | -0.0630688| 0.0196461| -3.210251| 0.0013262|  9.558495| -0.1015743| -0.0245632|\n\n\n:::\n:::\n\n\n\n\n-   The marginal effect of age is -0.0015153 (95% CI \\[-0.0026088, -0.0004219\\]). So, for each additional unit increase of age, the probability of being satisfied with mass transportation spending decreases by approximately 0.15 percentage points, holding other factors constant (p = 0.0066050).\n\n-   The marginal effect of SES is 0.0015304 (95% CI \\[-0.0023219, -0.0007388\\]). For each one-unit increase in the socioeconomic index, the probability of being satisfied with mass transportation spending decreases by approximately 0.15 percentage points, holding other variables constant.\n\n-   The marginal effect for being female compared to male is 0.0630688 (95% CI \\[-0.1015743, -0.0245632\\]). This indicates that females are, on average, about 6.31 percentage points more likely than males to be satisfied with mass transportation spending, holding other factors constant.\n\n## Model comparison\n\n-   Now let’s see whether a person’s political views has a significant impact on their odds of being satisfied with spending on mass transportation, after accounting for the demographic factors.\n\n> Conduct a drop-in-deviance/likelihood ratio test to determine if polviews is a significant predictor of attitude towards spending on mass transportation. Name these two models `fit2` and `fit3`, respectively. Compare the two models.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2 <- glm(mass_trans_spend_right~age + sex +sei10, data = data, family = binomial(link=\"logit\"))\n\nfit3 <- glm(mass_trans_spend_right ~ polviews + age + sex + sei10, data = data, family = binomial(link = \"logit\"))\n\ntest_likelihoodratio(fit2, fit3) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|     |Name |Model | df| df_diff|     Chi2|  p|\n|:----|:----|:-----|--:|-------:|--------:|--:|\n|fit2 |fit2 |glm   |  4|      NA|       NA| NA|\n|fit3 |fit3 |glm   | 10|       6| 63.02844|  0|\n\n\n:::\n:::\n\n\n\n\n> Is the model with polviews better than the model without?\n\n-   Yes (LRT show p\\<.001)\n\n## Visualization\n\n-   Let’s plot the results\n\n-   We next use the model to produce visualizations:\n\n    -   Given the code below, interpet what is being plotted:\n\n        -   pol_plot : support for mass transit spending is highest for extreme conervatives\n\n        -   sex_plot : women more likely to support more spending\n\n        -   ses_plot: lower SES also predicts more spending support\n\n    ::: callout-tip\n    -   adjust the various settings in your plot to make it look professional.\n\n    -   You can use `ggeffects` to get the predicted probabilities for these models.\n    :::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggeffects)\n\n\ncolors <- c(\"Extremely liberal\" = \"black\",\n            \"Liberal\" = \"#0e2f44\",  # Dark blue\n            \"Slightly liberal\" = \"#1d5a6c\",  # Less dark blue\n            \"Moderate\" = \"#358ca3\",  # Medium blue\n            \"Slghtly conservative\" = \"#71b9d1\",  # Light blue\n            \"Conservative\" = \"#a6dcef\",  # Lighter blue\n            \"Extrmly conservative\" = \"#d0f0fd\")  # Very light blue\n\npp_pol <- ggemmeans(fit3, terms = c(\"polviews\"))\n\n# Adjusted plot with gradient colors\npol_plot <- ggplot(pp_pol, aes(x = x, y = predicted, color = x)) +\n  geom_point(size = 2) +\n  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +\n  scale_color_manual(values = colors) +\n  labs(title = \"Effect of Political Views on Satisfaction with Mass Transportation\",\n       x = \"Political Views\", y = \"Predicted Probability\",\n       color = \"Political Views\") +\n  theme_minimal()\n\npol_plot\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-18-1.png){width=1152}\n:::\n\n```{.r .cell-code}\npp_sex <- ggemmeans(fit3, terms = c(\"sex\"))\n\nsex_plot <- ggplot(pp_sex, aes(x = x, y = predicted, color = x)) +\n  geom_point(size = 2) +\n  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +\n  labs(title = \"Effect of Sex on Satisfaction with Mass Transportation\",\n       x = \"Sex\", y = \"Predicted Probability\",\n       color = \"Sex\") +\n  theme_minimal()\nsex_plot\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-18-2.png){width=1152}\n:::\n\n```{.r .cell-code}\npp_sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Predicted probabilities of mass_trans_spend_right\n\nsex    | Predicted |     95% CI\n-------------------------------\nMale   |      0.48 | 0.44, 0.51\nFemale |      0.55 | 0.51, 0.58\n\nAdjusted for:\n*   age = 48.90\n* sei10 = 46.07\n```\n\n\n:::\n\n```{.r .cell-code}\npp_ses <- ggemmeans(fit3, terms = \"sei10\")\n\n\nses_plot <-  ggplot(pp_ses, aes(x = x, y = predicted)) +\n  geom_line(color = \"#2c7fb8\", size = 1) + \n  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), fill = \"#2c7fb8\", alpha = 0.2) +  # Add a confidence interval band\n  labs(title = \"Effect of SES on Satisfaction with Mass Transportation\",\n       x = \"Socioeconomic Status\", y = \"Predicted Probability\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")  \nses_plot\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-18-3.png){width=1152}\n:::\n:::\n\n\n\n\n## Model Assumptions\n\n-   Is the logistic model a good choice for this data?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinned_residuals(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: About 86% of the residuals are inside the error bounds (~95% or higher would be good).\n```\n\n\n:::\n:::\n\n\n\n\n::: callout-note\nAnswer: Doesn't seem like it because the warning says that we're only at 86% of the residuals being inside the error bounds and we should be closer to 95%\n:::\n\n## Model fit\n\n-   Calculate the $R^2$ for this model\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr2_mcfadden(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Generalized Linear Regression\n       R2: 0.010\n  adj. R2: 0.009\n```\n\n\n:::\n:::\n\n\n\n\n> R2 interpretation: This model accounts for .01% of the data which is not great\n>\n> Next, Take a look at the binned residual plots for each continuous predictor variable and look at linearity. Is there a predictor that sticks out? What can we do to improve model fit in this case?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"sei10\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: About 88% of the residuals are inside the error bounds (~95% or higher would be good).\n```\n\n\n:::\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"age\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOk: About 98% of the residuals are inside the error bounds.\n```\n\n\n:::\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"sei10\") %>% plot(show_dots=TRUE)\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"age\") %>% plot(show_dots=TRUE)\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-21-2.png){width=672}\n:::\n:::\n\n\n\n\n::: callout-note\n-   ::: callout-note\n    Age is a better predictor than SEI, given that age has less residuals outside of bound than sei10 does? Also nonlinear trend here could indicate transformations are required.\n    :::\n:::\n\n## Testing Polviews\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(fit3, \"polviews\") %>% pairs() %>% as.data.frame() %>% filter(p.value < .05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                                   estimate        SE  df z.ratio\n Extremely liberal - Moderate             -0.9266262 0.1950664 Inf  -4.750\n Extremely liberal - Slghtly conservative -0.8487137 0.2127293 Inf  -3.990\n Extremely liberal - Conservative         -0.9935486 0.2108369 Inf  -4.712\n Extremely liberal - Extrmly conservative -1.3402621 0.2792876 Inf  -4.799\n Liberal - Moderate                       -0.7090022 0.1308520 Inf  -5.418\n Liberal - Slghtly conservative           -0.6310897 0.1555805 Inf  -4.056\n Liberal - Conservative                   -0.7759246 0.1532081 Inf  -5.065\n Liberal - Extrmly conservative           -1.1226380 0.2392048 Inf  -4.693\n Slightly liberal - Extrmly conservative  -0.7334002 0.2412625 Inf  -3.040\n p.value\n  <.0001\n  0.0013\n  0.0001\n  <.0001\n  <.0001\n  0.0010\n  <.0001\n  0.0001\n  0.0382\n\nResults are averaged over the levels of: sex \nResults are given on the log odds ratio (not the response) scale. \nP value adjustment: tukey method for comparing a family of 7 estimates \n```\n\n\n:::\n\n```{.r .cell-code}\nemmeans(fit3, \"polviews\", type=\"response\") %>% pairs() %>% as.data.frame() %>% filter(p.value < .05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                                 odds.ratio         SE  df null\n Extremely liberal / Moderate              0.3958871 0.07722426 Inf    1\n Extremely liberal / Slghtly conservative  0.4279651 0.09104070 Inf    1\n Extremely liberal / Conservative          0.3702605 0.07806458 Inf    1\n Extremely liberal / Extrmly conservative  0.2617771 0.07311109 Inf    1\n Liberal / Moderate                        0.4921350 0.06439684 Inf    1\n Liberal / Slghtly conservative            0.5320118 0.08277063 Inf    1\n Liberal / Conservative                    0.4602780 0.07051835 Inf    1\n Liberal / Extrmly conservative            0.3254202 0.07784206 Inf    1\n Slightly liberal / Extrmly conservative   0.4802732 0.11587191 Inf    1\n z.ratio p.value\n  -4.750  <.0001\n  -3.990  0.0013\n  -4.712  0.0001\n  -4.799  <.0001\n  -5.418  <.0001\n  -4.056  0.0010\n  -5.065  <.0001\n  -4.693  0.0001\n  -3.040  0.0382\n\nResults are averaged over the levels of: sex \nP value adjustment: tukey method for comparing a family of 7 estimates \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n:::\n\n\n\n\n-   Conservatives are .37 times more likely to support mass transit spending compared to extremely liberal and liberal\n\n-   Extreme liberals are .42 times more likely to support spending compared to conservatives, moderates and slight conservatives\n\n-   Extrm conservatives are .48 times more likely to support mass spending than liberals and slight liberals\n\n-   Liberals are .49 times more likely to support spending than moderates and slight conservatives.\n\n(I am not confident about these results above)\n\n## Conclusion\n\nPolitical views are the best predictor of mass transportation spending opinions, given the large reduction in deviance. Age and sex perform almost equally, but sei10 is not all that helpful\n\n\n\n\n\n|         | Df|  Deviance| Resid. Df| Resid. Dev|  Pr(>Chi)|\n|:--------|--:|---------:|---------:|----------:|---------:|\n|NULL     | NA|        NA|      2589|   3581.340|        NA|\n|polviews |  6| 64.575385|      2583|   3516.765| 0.0000000|\n|age      |  1| 12.999334|      2582|   3503.766| 0.0003116|\n|sex      |  1| 12.946009|      2581|   3490.820| 0.0003206|\n|sei10    |  1|  8.051857|      2580|   3482.768| 0.0045457|\n\n\n\nTable 1\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 1: Effect of Sex on Satisfaction with Mass Transportation](Lab-Logistic-Q_files/figure-html/plot-sexviews-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 2: Effect of SES  on Satisfaction with Mass Transportation](Lab-Logistic-Q_files/figure-html/plot-sesviews-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 3: Effect of Political Views on Satisfaction with Mass Transportation](Lab-Logistic-Q_files/figure-html/plot-polviews-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "Lab-Logistic-Q_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}